version: '3'
services:
  mongodb:
    image: mongo:3.2.6
    ports:
      - 27017:27017

  mongo-seed:
    image: mongo:3.2.6
    volumes:
      - ./seed:/seed
    command:
      "./seed/runSeed.sh"
    depends_on:
      - mongodb

  oauth-provider-example:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - MONGODB=mongodb://mongodb:27017/oauth
    depends_on:
      - mongodb

